name: Sync docs to Google Drive

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  sync-to-drive:
    environment: docs
    runs-on: ubuntu-latest
    env:
      PARENT_FOLDER_ID: "11RfZHdoJ1UnaTk4rHYZQoZ8nb0F4qPpV"
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. rcloneをインストール
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      # 2. rcloneの認証情報を設定
      - name: Configure rclone
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          mkdir -p ~/.config/rclone
          echo "[drive]" > ~/.config/rclone/rclone.conf
          echo "type = drive" >> ~/.config/rclone/rclone.conf
          echo "scope = drive" >> ~/.config/rclone/rclone.conf
          echo "service_account_file_path = /tmp/gdrive_credentials.json" >> ~/.config/rclone/rclone.conf
          echo "$GDRIVE_CREDENTIALS" > /tmp/gdrive_credentials.json

      # 3. 変更があったファイルを取得
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      # 4. 追加・更新されたファイルをアップロード
      - name: Upload added/modified files
        if: steps.changed-files.outputs.added_files != '' || steps.changed-files.outputs.modified_files != ''
        run: |
          echo "Uploading added/modified files..."
          for file in ${{ steps.changed-files.outputs.added_files }} ${{ steps.changed-files.outputs.modified_files }}; do
            rclone copy "$file" "drive:$PARENT_FOLDER_ID/$file" --create-empty-src-dirs
          done
          echo "✅ Files uploaded."

      # 5. 削除されたファイルをGoogle Driveから削除
      - name: Delete removed files
        if: steps.changed-files.outputs.deleted_files != ''
        run: |
          echo "Deleting removed files..."
          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            # パス構造を維持したまま削除
            rclone delete "drive:$PARENT_FOLDER_ID/$file"
          done
          echo "✅ Files deleted."
